# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e77c8ab8c85736db318337c0ff9a14b5f1b68b590e57ae3012804103e309260254ba990a5ca17848bfbba498c47d8c613feafc583906f6bdd82433a16ac3fb59

test:
  secret_key_base: 991de77eb4536a6bb26587c53374ca3d36a46e683d642b04bcae26ddac47538e3801ba8dc7df10d32baa1d40873638d4e88b107d5451f1ebabc902d7436001c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
